language: C

install:
  - CHANNEL=http://eupsforge.net/conda/dev ./setup/install.sh lsst-sims nose pandas
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - setup lsst_sims
  - eups declare -r . Twinkles -t current
  - setup Twinkles

cache:
  directories:
  - $HOME/miniconda.tarball

script:
  - nosetests
